renew type checking
PaddlePaddle/PaddleTS pull request #249
Opened 2022-11-09 14:54 UTC by linjing-lab

- change "pyplot" to plt(matplotlib.pyplot)
- change Optional[str, int] to Optional[Union[str, int]]
- add Optional to type checking

2022-11-09 14:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleTS?pullRequest=249) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleTS?pullRequest=249) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleTS?pullRequest=249) it.</sub>

2022-11-10 02:04 UTC, kehuo commented on paddlets/analysis/analysis_report.py
> +    def export_docx_report(self, path: Optional[str] = ".", file_name: Optional[str] = "analysis_report.docx") -> None:
should NOT be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:04 UTC, kehuo commented on paddlets/analysis/analysis_report.py
> +    def export_json_report(self, log: Optional[bool] = True) -> Dict:
should NOT be None, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:05 UTC, kehuo commented on paddlets/analysis/analysis_report.py
> +    def get_all_analyzers_names(self, log: Optional[bool] = True) -> List[str]:
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:06 UTC, kehuo commented on paddlets/analysis/frequency_domain.py
> +    def __init__(self, fs: Optional[float] = 0, norm: Optional[bool] = True, half: Optional[bool] = True, **kwargs):
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:06 UTC, kehuo commented on paddlets/analysis/frequency_domain.py
> +        fs: Optional[float] = 1.0,
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:06 UTC, kehuo commented on paddlets/analysis/frequency_domain.py
> +        window: Optional[Union[str, Tuple[str], List[str]]] = 'hann',
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:07 UTC, kehuo commented on paddlets/analysis/frequency_domain.py
> +        nperseg: Optional[int] = 256,
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:07 UTC, kehuo commented on paddlets/analysis/frequency_domain.py
> +        detrend: Optional[Union[str, bool]] = False,
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:07 UTC, kehuo commented on paddlets/analysis/frequency_domain.py
> +        return_onesided: Optional[bool] = True,
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:07 UTC, kehuo commented on paddlets/analysis/frequency_domain.py
> +        boundary: Optional[Union[str, None]] = 'zeros',
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:07 UTC, kehuo commented on paddlets/analysis/frequency_domain.py
> +        padded: Optional[bool] = True,
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:07 UTC, kehuo commented on paddlets/analysis/frequency_domain.py
> +        axis: Optional[int] = -1,
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:08 UTC, kehuo commented on paddlets/analysis/time_domain.py
> +                 order: Optional[int] = 1,
Line39 - Line42 should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:09 UTC, kehuo commented on paddlets/analysis/time_domain.py
> +        period_dict: Optional[dict] = {},
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:09 UTC, kehuo commented on paddlets/analysis/time_domain.py
> +                 method: Optional[str] = 'pearson',
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:09 UTC, kehuo commented on paddlets/analysis/time_domain.py
> +                 lag: Optional[int] = 0,
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:10 UTC, kehuo commented on paddlets/automl/autots.py
> +            verbose: Optional[int] = 4
Line95 - Line105 and Line107 - Line108 should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:10 UTC, kehuo commented on paddlets/automl/autots.py
> +            cpu_resource: Optional[float] = 1.0,
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:10 UTC, kehuo commented on paddlets/automl/autots.py
> +            gpu_resource: Optional[float] = 0
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:11 UTC, kehuo commented on paddlets/automl/optimize_runner.py
> +                 skip_chunk_len: Optional[int] = 0,
Line113 and Line 114 should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:11 UTC, kehuo commented on paddlets/automl/optimize_runner.py
> +                 gpu_resource: Optional[float] = 0,
Line 116 - Line123 should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:12 UTC, kehuo commented on paddlets/datasets/splitter.py
> +              return_index: Optional[bool] = False) -> Union[TSDataset, pd.DatetimeIndex, pd.RangeIndex]:
should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:16 UTC, kehuo commented on paddlets/datasets/splitter.py
> +                 verbose: Optional[bool] = True) -> None:
(1) Line309 n_splits should Not be Optional.
(2) Line310 can be either Optional[int] = None, or Union[int, None] = None. The reason is that Optional[x] is equivalent to Union[x, None].
(3) Line311 skip_size  should Not be Optional.
(4) Line313 verbose should Not be Optional.
Refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:16 UTC, kehuo commented on paddlets/datasets/splitter.py
> +                 skip_size: Optional[int] = 0,
Line483 skip_size should Not be Optional, refers to  https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:16 UTC, kehuo commented on paddlets/datasets/splitter.py
> +                 verbose: Optional[bool] = True) -> None:
Line484 verbose should Not be Optional, refers to  https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:16 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +        drop_tail_nan: Optional[bool] = False,
Line89 drop_tail_nan should Not be Optional, refers to  https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:17 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +    def to_dataframe(self, copy: Optional[bool]=True) -> pd.DataFrame:
Line258 copy should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:17 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +    def to_numpy(self, copy: Optional[bool]=True) -> np.ndarray:
Line274 copy should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:17 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +        after: Optional[bool]=True
Line294 after should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:17 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +        after: Optional[bool]=True
Line360 copy should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:18 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +        drop_tail_nan: Optional[bool] = False,
Line781 - Line784 should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:19 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +        drop_tail_nan: Optional[bool] = False,
Line858 - Line861 should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:19 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +        type: Optional[str] = 'known_cov'
Line1485 should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:19 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +             central_quantile: Optional[float] = 0.5,
Line1660 - Line1662 should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:20 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +                                low_quantile: Optional[float] = 0.05,
Line1804 should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:20 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +                                high_quantile: Optional[float] = 0.95,
Line1805 should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:20 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +    def concat(cls, tss: List["TSDataset"], axis: Optional[int] = 0, drop_duplicates: Optional[bool]=True, keep: Optional[str]='first') -> "TSDataset":
Line1966 axis,  drop_duplicates, keep should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:21 UTC, kehuo commented on paddlets/datasets/tsdataset.py
> +    def sort_columns(self, ascending: Optional[bool] = True):
Line2074 ascending should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:21 UTC, kehuo commented on paddlets/ensemble/ensemble_forecaster_base.py
> +                 skip_chunk_len: Optional[int] = 0,
Line35 skip_chunk_len should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:22 UTC, kehuo commented on paddlets/ensemble/ensemble_forecaster_base.py
> +    def save(self, path: str, ensemble_file_name: Optional[str] = "paddlets-ensemble-partial.pkl") -> None:
Line155 ensemble_file_name should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:22 UTC, kehuo commented on paddlets/ensemble/ensemble_forecaster_base.py
> +    def load(path: str, ensemble_file_name: Optional[str] = "paddlets-ensemble-partial.pkl") -> "EnsembleForecasterBase":
Line189 ensemble_file_name should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:23 UTC, kehuo commented on paddlets/ensemble/stacking_ensemble_forecaster.py
> +                 verbose: Optional[bool] = False
Line44 - Line48  use_backtest, resampling_strategy, split_ratio, split_ratio, k_fold, verbose should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:24 UTC, kehuo commented on paddlets/ensemble/weighting_ensemble_forecaster.py
> +                 verbose: Optional[bool] = False
Line40 - Line41 mode, verbose should Not be Optional, refers to https://docs.python.org/3/library/typing.html#typing.Optional

2022-11-10 02:29 UTC, kehuo requested changes
Thanks for the commit. As according to [python typing.Optional doc](https://docs.python.org/3/library/typing.html#typing.Optional), only if an explicit value of None is allowed for an argument, the use of typing.Optional is appropriate, so please remove all inappropriate Optional type checking.

2022-11-10 04:04 UTC, linjing-lab commented
> Thanks for the commit. As according to [python typing.Optional doc](https://docs.python.org/3/library/typing.html#typing.Optional), only if an explicit value of None is allowed for an argument, the use of typing.Optional is appropriate, so please remove all inappropriate Optional type checking.

ok

2022-11-10 04:06 UTC, closed without merging