[New Feature] add timesnet for forecast task
PaddlePaddle/PaddleTS pull request #416
Opened 2023-07-05 09:15 UTC by Sunting78

2023-07-11 03:30 UTC, shiyutang requested changes
感觉code style有点问题，可以安装precommit统一下风格。

2023-07-11 03:30 UTC, shiyutang commented on configs/longterm_forecast/timesnet_ECL.yaml
> +
删除不必要的空格。

2023-07-11 03:30 UTC, shiyutang commented on paddlets/models/forecasting/dl/paddle_base_impl.py
> +                logger.info('lr: {}'.format(self._scheduler.get_lr()))
要记录epoch对应的lr才知道有没有对齐，对齐后删除统一在训练一个epoch记录所有参数也可以

2023-07-11 06:20 UTC, Sunting78 commented on paddlets/models/forecasting/dl/paddle_base_impl.py
> +                logger.info('lr: {}'.format(self._scheduler.get_lr()))
已验证

2023-07-11 10:56 UTC, shiyutang requested changes

2023-07-11 12:31 UTC, Sunting78 commented on paddlets/models/classify/dl/timesnet.py
> +    return period, xf.abs().mean(axis=-1).index_select(
done

2023-07-12 02:28 UTC, shiyutang commented on train.py
> +        action='store_false')
为什么是store false呢，默认应该是加了这个args之后开始训练？ 因为是写的do_train，下面do_eval 同理

2023-07-12 02:28 UTC, shiyutang commented on train.py
> +            ts_test = time_feature_generator.fit_transform(ts_test)
不是所有的数据集都有ts_test，不过也可后面涉及到再兼容。

2023-07-12 02:28 UTC, shiyutang commented on paddlets/models/classify/dl/paddle_base.py
> +            loss_fn: Callable[..., paddle.Tensor]=F.cross_entropy,
我记得不是所有都是CE损失，后面可能需要单独设置一下

2023-07-12 02:44 UTC, Sunting78 commented on paddlets/models/classify/dl/paddle_base.py
> +            loss_fn: Callable[..., paddle.Tensor]=F.cross_entropy,
ok 分类目前都是

2023-07-12 02:45 UTC, Sunting78 commented on train.py
> +            ts_test = time_feature_generator.fit_transform(ts_test)
test初始化为None了fit_transform 如果是None会返回None

2023-07-12 02:46 UTC, Sunting78 commented on train.py
> +        action='store_false')
默认最好不加这个参数 要不每次跑都得加 我把名字改成了no_eval 
train暂时删除了 后面会补上加load checkpoint的

2023-07-12 03:00 UTC, shiyutang commented on train.py
> +        action='store_false')
嗯嗯好的～

2023-07-12 03:01 UTC, shiyutang approved these changes
LGTM

2023-07-12 12:40 UTC, merged